<?php

/**
 * @file
 * DigitalTheme custom functionality.
 *
 * Copyright (C) 2026 Adrian Zalewski
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License,
 * or (at your option) any later version.
 */

/**
 * @file
 * Digital Theme theme file.
 */




function digitaltheme_preprocess_html(&$variables){

$schema =
\Drupal::service('digital.schema_generator')
->build();


$variables['schema_json'] =
json_encode(
$schema,
JSON_PRETTY_PRINT |
JSON_UNESCAPED_SLASHES
);

}






/**
 * Implements hook_theme_suggestions_taxonomy_term_alter().
 */
function digitaltheme_theme_suggestions_taxonomy_term_alter(array &$suggestions, array $variables) {
  /** @var \Drupal\taxonomy\TermInterface $term */
  $term = $variables['elements']['#taxonomy_term'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');
  // Add view mode theme suggestions.
  $suggestions[] = 'taxonomy_term__' . $sanitized_view_mode;
  $suggestions[] = 'taxonomy_term__' . $term->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'taxonomy_term__' . $term->id() . '__' . $sanitized_view_mode;
}
